--- Chat events listed exclusively in Chat, even if related to party/guild/etc.
---@alias Event
--- | TODO_Event
--- | EventActionBar
--- | EventAuction
--- | EventBattleground
--- | EventChat
--- | EventDeath
--- | EventGuild
--- | EventHonor
--- | EventItem
--- | EventLoot
--- | EventMail
--- | EventMap
--- | EventParty
--- | EventPet
--- | EventQuest
--- | EventSpell
--- | EventTrade
--- | EventUnit
